### PR TITLE
Fix for Reindent some individual lines after merging

### PR DESCRIPTION
**Pull request by ashwinpadmakumar**
Fix for issue #136 

Indentation was fixed for the mentioned files.
UsersJpaCrudServiceImpl.java was fixed already

### CODE REVIEW

**Comment by ashwinpadmakumar** [comment]
@bglamadrid Please review the PR and please let me know if there are any concerns. Thanks

**Review by bglamadrid — CHANGES_REQUESTED** [review]
@ashwinpadmakumar thank you

`src/test/java/org/trebol/jpa/services/crud/UsersJpaCrudServiceTest.java` still needs correct indentation.

I didn't notice it before but there is a problem here. Some of these lines are partially indented with both tabs and whitespaces, while the ideal is to only use whitespaces to indent.

Please see if you can fix it.

**Comment by ashwinpadmakumar** [comment]
@bglamadrid Sure. Will take a look again.

**Comment by ashwinpadmakumar** [comment]
@bglamadrid Just a suggestion. While going throw the classes (at least the test classes for now) I see that the formatting is not uniform. Can I format all the test classes with this configuration?
image
To summarize the above configuration, all the lines have an indentation of 4 spaces (relative to its previous line)

**Comment by bglamadrid** [comment]
> @bglamadrid Just a suggestion. While going throw the classes (at least the test classes for now) I see that the formatting is not uniform. Can I format all the test classes with this configuration? image To summarize the above configuration, all the lines have an indentation of 4 spaces (relative to its previous line)

Thanks for asking! No, please use an indentation of 2 spaces.
This reminds me that I should create an `.editorconfig` file so that this doesn't ever pose a problem.

**Pull request closed without merging**
