### PR TITLE
fix: remove unnecesary condition

### PR DESCRIPTION
**Pull request by Angel-M-R**
Fixes sonar cloud issue
#186

### CODE REVIEW

**Review by NyorJa — CHANGES_REQUESTED** [review]
what IDE are you using? it seems you introduce a lot of spaces. The requirement is to remove the null checking for price

**Comment by mepox** [comment]
> what IDE are you using? it seems you introduce a lot of spaces. The requirement is to remove the null checking for price

I was wondering as well why the whole file has been marked as changed.

**Review by mepox — APPROVED** [review]

**Comment by bglamadrid** [comment]
Hi @Angel-M-R ! Thank you for your interest in the project. I appreciate your effort and time put into this PR. However I am most curious, just like Nyorja and mepox...

It bugs me that your commit states you're overwriting the entire file. This isn't very good practice - how do you work with Git? Which IDE do you use?

**Comment by Angel-M-R** [comment]
Hello im using VS Code, it's been weird for me too view the entire file with changes because i only changed one line, let me try to fix it with other IDE

**Comment by NyorJa** [comment]
> Hello im using VS Code, it's been weird for me too view the entire file with changes because i only changed one line, let me try to fix it with other IDE

Please use Intellij

**Review by mepox — APPROVED** [review]

**Comment by bglamadrid** [comment]
@Angel-M-R As Nyorja said, we highly recommend IntelliJ IDEA, for it has a lot of built-in tooling in place to analyze and improve your Java code.

I also want to give you another tip.

- Try to avoid force-pushing branches, unless you're _absolutely_ sure of what you're doing. 

I learned this the hard way; I messed up commit history once. PRs particularly can be squash-merged and cleansed; you don't have to overwrite your commit history 😉

Regardless of the above, you did a good job. Thank you!

**Pull request merged**
