### PR TITLE
Used entrySet in place of keySet

### LINKED ISSUE #179: [Sonar] Iterate over the "entrySet" instead of the "keySet" in `src/main/java/org/trebol/config/CorsConfigurationSourceBuilder.java`
## Summary

- [Source Sonar issue URL](https://sonarcloud.io/project/issues?issues=AYKvHFqnl4ZcazHMfJ5c&open=AYKvHFqnl4ZcazHMfJ5c&id=trebol-ecommerce_spring-boot-backend)
- Issue type: `Code Smell`
- Severity: `Major`
- Technical debt: `5min effort`

### PR DESCRIPTION
**Pull request by logesr**
## PR Checklist

- [x] Read the [contribution guidelines](/CONTRIBUTING.md)
- [x] Added a brief description of these changes to the top of the [changelog](/CHANGELOG.md)
- [x] Changes in code meet test criteria (running `mvn test` returns exit code 0, without errors)

## PR Type

- [x] Refactoring (changes that do not affect API nor functionality)

## Summary

Used entrySet in place of keySet which serves better in this purpose when we iterate to get both key and value. Closes #179

### CODE REVIEW

**Comment by bglamadrid** [comment]
Hi @logesr! Thanks for your contribution. 

I'm a little concerned though, these commits are forcing a whole-file overwrite operation, yet these changes should just span a couple lines of code.

What IDE do you use? How do you work with Git?

**Review by NyorJa — CHANGES_REQUESTED** [review]
What IDE are you using? It seems you introduced a lot of spaces

**Comment by logesr** [comment]
Hi @NyorJa and @bglamadrid, I am using intellij IDEA. Not sure how these spaces came in. Will check it out

**Comment by bglamadrid** [comment]
Thank you for coming back to us @logesr 

It still bothers me that this PR overwrites the entirety of the files involved.

I know this may take some time, but can you please start over?
Backup these files, back to `main`, create a new branch, paste your backup files on it, commit, push and create a new PR just like this one. 
If that PR performs _just_ the intended changes then I'll be sure to merge it 👍

**Comment by logesr** [comment]
Sure thing @bglamadrid. Will create a new pull request

**Pull request closed without merging**
