### PR TITLE
fix: sonar issue always false

### PR DESCRIPTION
**Pull request by Angel-M-R**
Fixes sonar cloud issue
#184

### CODE REVIEW

**Review by NyorJa — CHANGES_REQUESTED** [review]
Please check formatting

**Comment by NyorJa** [comment]
> > Please check formatting
> 
> Where exactly? Empty Line in 66, 68 and 71?

Not exactly the specific line but the whole class itself introduce a new format. I'm not sure if it follows to spaces

**Comment by Angel-M-R** [comment]
Hello @NyorJa could you check please?

**Review by mepox — APPROVED** [review]
Hi @Angel-M-R ! Thanks for fixing your formatting.

**Review by bglamadrid — CHANGES_REQUESTED** [review]
Please remove the failing test in `CustomersConverterJpaServiceImplTest` (Line 53) that was related to raising a `BadInputException` when this condition was true.

**Comment by mepox** [comment]
> Please remove the failing test in `CustomersConverterJpaServiceImplTest` (Line 53) that was related to raising a `BadInputException` when this condition was true.

Good catch, sorry 😄 I actually manually pulled the PRs and ran `mvn test` but I probably skipped this one..... 😐

**Comment by Angel-M-R** [comment]
Done, thank you @bglamadrid

**Pull request merged**
